spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-service:30006/ftms-local-test?useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  flyway:
    enabled: true
    locations: ["classpath:/db/migration"]
    out-of-order: false

feign:
  okhttp:
    enabled: true
